### ISSUE TITLE
Dies solltest du drinngend Ändern!

### ISSUE THREAD

**Issue by KevinKrueger** [Tutorialwork/Adventskalender#1]
Ganz bedenklicher Programmierstil!

Ein haufen if schleifen die im grunde genommen das selbe erledigen aber sich nur die Zahlen ändern!

Überarbeite das dringend mal!
Und immer schön Code kommentieren!

**Comment by twhx99** [comment]
Ich möchte beifügen, dass zudem generelle Code Convention nicht eingehalten wurden.
Um jedoch auch konstruktive Kritik zu äußern möchte ich einige Punkte nennen und erläutern, wie es "richtig" aussehen sollte.

1. Datei- und Klassennamen mit Großbuchstaben beginnen
> Klassennamen, sowie die dazugehörigen Dateinamen (XYZ.java) müssen mit einem Großbuchstaben beginnen. Der Standard Java-Compiler setzt dies sogar für die erfolgreiche Kompilierung voraus, sofern nichts anderes eingestellt wurde. Selbst die JetBrains IntelliJ Idea sollte diesbezüglich bereits eine Warnung angezeigt haben.
2. Wiederverwendbarkeit und Wartbarkeit von Quellcode
> Ein beachtlicher Teil deines Quellcodes weist Redundanzen auf bzw. Anweisungen / Codezeilen werden ohne signifikante Änderungen wiederholt. 
So gibt es die Zeile `configcfg.addDefault("Reward.1", "give %player% minecraft:diamond 1");` in 24-facher Ausführung. Lediglich die Zahl wurde angepasst. Eine simple Schleife (Wertebereich 1-24) hätte das ganze auf 3 Zeilen gekürzt und somit den Quellcode, sowie die Lesbarkeit optimiert.
In der Klasse adventskalender findet man ähnliches vor. Hier wurde die if/else-Anweisung, sowie der Aufruf im EventHandler in ebenso mehrfacher Form nur angepasst. Hätte man für eben jene Anweisungen Funktionen mit Parametern angefertigt würde der Quellcode um ein Vielfaches kleiner, lesbarer und vor allem Wartbarer sein.
3. Kommentare
> Quellcode ist teilweise selbsterklärend und nicht jeder Getter oder Setter braucht einen Kommentar, das ist klar. Doch bei Umfangreichen Methoden oder Programmabläufen empfiehlt es sich vor allem Code-Bestandteile die nicht selbsterklärend sind mit einem Kommentar zu versehen. Einerseits hilft es andere, die möglicherweise ein benutztes Framework nicht kennen und zudem dir selbst, wenn du nach 2 Jahren wieder auf deinen Quellcode schaust, damit du weißt, was der Quellcode genau an dieser Stelle für eine Aufgabe hat.
4. Angaben über das Projekt und verwendete Frameworks, Bibliotheken oder APIs
> Generell empfiehlt es sich, sobald externe Bibliotheken verwendet werden, diese in irgendeiner Form zu dokumentieren. Das schließt den Namen, Herausgeber, die Version, sowie den Bezugsort von Bibliotheken mit ein. Du selbst hat die Projekt-Iml von Idea mit ins das Projektgeladen, wo zwar heraus zu erkennen ist, dass du die spigot-api der Minecraft 1.8.8 verwendet hast, aber nicht wo man diese her bekommt. Wer sich auskennt hat Glück, wer nicht hat keines.
Meine Empfehlung bzw. ein Best Practise: Dokumentiere in einer Datei (z.B. Readme.md) welche Bibliotheken du verwendest und wo man sich diese Herunterladen kann. Noch besser ist, du benutzt (falls die Bibliothek es unterstützt) ein Build-Tool wie Maven oder Gradle. In diesen werden alle Abhängigkeiten definiert und jeder der dein Projekt öffnet, kann sich die Abhängigkeiten automatisch herunterladen lassen. Weiterhin sorgt es dafür, dass auch die verwendeten Versionen (Versionsbezeichnungen) der Bibliotheken mit versioniert werden.
